package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/doipster/asset_cracker/service/internal/engine"
)

// emitMigration writes db/migrations/0020_kalshi15m_v3_versions.sql from frozen-params.json and
// test-result.json (section 7; the plan's "migration 0013", renumbered because 0013 to 0019 are
// taken by history). It refuses unless R1 and R2 both passed, and it refuses whenever
// engine.Scalper or engine.Value refuses the params: every number must carry its provenance and
// the four measured ones must be measured. There is no flag that relaxes that.
//
// drift_tol: the protocol measured it in step S5 against a live second engine on the scratch
// database, and that engine is stopped. Until the owner's third amendment says what stands in
// its place, engine.Validate refuses the versions here, and this command emits nothing.
const migrationName = "0020_kalshi15m_v3_versions.sql"

func emitMigration(r repo) error {
	var frozen frozenParams
	if ok, err := readJSON(r.researchPath(frozenFile), &frozen); err != nil {
		return err
	} else if !ok {
		return fmt.Errorf("refusing: %s does not exist", frozenFile)
	}
	if frozen.Lambda <= 0 {
		return errors.New("refusing: R1 failed (lambda 0); nothing is registered (section 8)")
	}
	var result testResult
	if ok, err := readJSON(r.researchPath(testResultFile), &result); err != nil {
		return err
	} else if !ok {
		return fmt.Errorf("refusing: %s does not exist; TEST has not been run", testResultFile)
	}
	if !result.R2.Pass {
		return fmt.Errorf("refusing: R2 failed (%s); nothing is registered (section 8)", result.R2.Verdict)
	}
	if result.Frozen.ProtocolSHA != frozen.ProtocolSHA || frozen.ProtocolSHA != protocolSHA {
		return errors.New("refusing: the result files and this tool were not made under the same protocol text")
	}
	resultSHA, err := sha256File(r.researchPath(frozenFile))
	if err != nil {
		return err
	}
	head, err := r.headSHA()
	if err != nil {
		return err
	}

	measured := func(value float64, note string) engine.Provenance {
		return engine.Provenance{Kind: engine.KindMeasured, Value: value, Note: note}
	}
	m := engine.Measured{
		Lambda:        measured(frozen.Lambda, fmt.Sprintf("M1, the lower one-sided 95%% bound, floored to 0.01, on TRAIN %s to %s", frozen.TrainFirstClose.Format(time.RFC3339), frozen.TrainLastClose.Format(time.RFC3339))),
		StaleCost:     measured(frozen.StaleCost, "M2: measured on the recorded TRAIN book at rows where the forecast alone would buy; no order; a proxy for v3's fills"),
		StaleCostSell: measured(frozen.StaleCostSell, "M2s: measured on the recorded TRAIN book at rows where the forecast alone would sell; no order; a proxy for v3's fills"),
		// No measurement exists (see the comment above). Validate decides whether this may stand.
		DriftTol:    engine.Provenance{Kind: engine.KindFact, Value: 0, Note: "no reference engine runs beside the third; the drift gate is open and the number decides nothing"},
		ProtocolSHA: protocolSHA,
		ResultSHA:   resultSHA,
	}
	scalper, err := engine.Scalper(m)
	if err != nil {
		return fmt.Errorf("refusing: Scalper v3 may not be registered: %w", err)
	}
	value, err := engine.Value(m)
	if err != nil {
		return fmt.Errorf("refusing: Value v3 may not be registered: %w", err)
	}
	sj, err := json.Marshal(scalper)
	if err != nil {
		return err
	}
	vj, err := json.Marshal(value)
	if err != nil {
		return err
	}
	hyp := func(name string) string {
		return fmt.Sprintf("%s v3: the parent's rules over the honest-fills engine (integer cents, paper fills from the displayed book), "+
			"with lambda %.2f, stale_cost %.4f and stale_cost_sell %.4f measured under protocol %s (result %s). "+
			"Judged live at the corrected threshold; R2 passing is permission to try, not evidence of edge.",
			name, frozen.Lambda, frozen.StaleCost, frozen.StaleCostSell, protocolSHA[:12], resultSHA[:12])
	}
	var b strings.Builder
	fmt.Fprintf(&b, "-- Scalper v3 and Value v3, as draft: the two versions the v3 measurement protocol permits.\n")
	fmt.Fprintf(&b, "-- Generated by cmd/measure3 emit-migration at %s from research/v3/frozen-params.json.\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "-- protocol sha-256 %s\n-- result   sha-256 %s\n-- tool git sha     %s\n", protocolSHA, resultSHA, head)
	fmt.Fprintf(&b, "-- A person sets probation from the buckets page; the live engine then seeds a $1,000 bucket.\n\n")
	b.WriteString("do $$ begin\n")
	b.WriteString("    if position('placeholder' in $params$" + string(sj) + string(vj) + "$params$) > 0 then\n")
	b.WriteString("        raise exception 'a placeholder number may not be registered';\n    end if;\nend $$;\n\n")
	for _, v := range []struct {
		name   string
		params []byte
	}{{"Scalper", sj}, {"Value", vj}} {
		fmt.Fprintf(&b, "insert into strategy_version (strategy_id, version, params, code_ref, hypothesis, parent_version_id, created_by, status)\n")
		fmt.Fprintf(&b, "select s.id, 3, $params$%s$params$::jsonb, %s, %s,\n", v.params, sqlString(head), sqlString(hyp(v.name)))
		fmt.Fprintf(&b, "       (select p.id from strategy_version p where p.strategy_id = s.id and p.version = 2),\n")
		fmt.Fprintf(&b, "       (select id from actor where handle = 'claude'), 'draft'\n")
		fmt.Fprintf(&b, "  from strategy s where s.family = 'kalshi15m' and s.name = %s\n", sqlString(v.name))
		// Only a dev plumbing row may be overwritten; a real row is never touched twice.
		fmt.Fprintf(&b, "on conflict (strategy_id, version) do update\n   set params = excluded.params, code_ref = excluded.code_ref, hypothesis = excluded.hypothesis\n")
		fmt.Fprintf(&b, " where strategy_version.hypothesis like 'DEV PLUMBING%%';\n\n")
	}
	path := filepath.Join(r.Root, "db", "migrations", migrationName)
	if _, err := os.Stat(path); err == nil {
		return fmt.Errorf("refusing: %s exists", path)
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s\n", path)
	return nil
}

func sqlString(s string) string { return "'" + strings.ReplaceAll(s, "'", "''") + "'" }
